const IMAGES = {
  navBarLogo: new URL("../landingPage/WorkSphereLogo.png", import.meta.url)
    .href,
  navBarLogoDark: new URL("../landingPage/logoDark.png", import.meta.url).href,
  image: new URL("../landingPage/image.png", import.meta.url).href,
  leftSide: new URL("../landingPage/leftSide.jpg", import.meta.url).href,
  heroImage: new URL("../landingPage/analytics.jpg", import.meta.url).href,
  hero: new URL("../landingPage/hero.png", import.meta.url).href,
  heroSecond1: new URL("../landingPage/heroSecond1.png", import.meta.url).href,
  heroSecond2: new URL("../landingPage/heroSecond2.png", import.meta.url).href,
  heroSecond3: new URL("../landingPage/heroSecond3.png", import.meta.url).href,
  man: new URL("../landingPage/man.jpg", import.meta.url).href,
  login: new URL("../landingPage/loginBackground.jpg", import.meta.url).href,
  teamImage: new URL("./aboutPage/teamImage.jpg", import.meta.url).href,
  teamCollaboration: new URL("./aboutPage/teamCollaboration.jpg", import.meta.url).href,
  projectManagement: new URL("./aboutPage/projectManagement.jpg", import.meta.url).href,
  Vinayak: new URL("./aboutPage/Vinayak.JPG", import.meta.url).href,
  Michael: new URL("./aboutPage/Michael.JPG", import.meta.url).href,
  Aisha: new URL("./aboutPage/Aisha.JPG", import.meta.url).href,
  David: new URL("./aboutPage/David.JPG", import.meta.url).href,
  Sophia: new URL("./aboutPage/Sophia.JPG", import.meta.url).href,
  Emma: new URL("./aboutPage/Emma.JPG", import.meta.url).href,
  Marcus: new URL("./aboutPage/Marcus.JPG", import.meta.url).href,
  // nexuimLogoWithName : new URL('../assets/landingPageAssets/nnnlogo1000[1].png ', import.meta.url).href,
  // homePicture : new URL('../assets/landingPageAssets/Human-Resources-square-ezgif.com-webp-to-png-converter.png ', import.meta.url).href,
  // success : new URL('../asedts/success/Animation - 1733548151550.json', import.meta.url).href,
  // logoSecond : new URL('../assets/landingPageAssets/nnn logooo 700[1].png', import.meta.url).href,
  // logoThird : new URL('../assets/landingPageAssets/nexium-icon.ico', import.meta.url).href,
  // superadmin : new URL('../assets/landingPageAssets/superadmin.jpg', import.meta.url).href,
};

export default IMAGES;
